library(dplyr)
library(tibble)
# variable thesaurus
variable_thesaurus <- tibble::tribble(
  # headers
  ~var_id, ~var_table, ~var_units,
  ~translation_eng, ~translation_spa, ~translation_cat,
  ~var_description_eng, ~var_description_spa, ~var_description_cat,
  # static table
  "plot_id", "static", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "animals_presence", "static", "count",
  "Animals presence", "Presencia de animales", "Presència d'animals",
  "", "", "",
  "mushrooms_production", "static", "",
  "Mushroom production", "Producción de setas", "Producció de bolets",
  "", "", "",
  "exported_water", "static", "",
  "Exported water", "Agua exportada", "Aigua exportada",
  "", "", "",
  "carbon_sequestration", "static", "",
  "Carbon sequestration", "Carbono secuestrado", "Carboni segrestat",
  "", "", "",
  "soil_organic_carbon", "static", "",
  "Soil organic carbon", "Carbono orgánico del suelo", "Carboni orgànic del sòl",
  "", "", "",
  "riparian_forest_cover", "static", "%",
  "Riparian forest cover", "Cobertura de bosques de ribera", "Cobertura de boscos de ribera",
  "", "", "",
  "slope_forest_cover", "static", "%",
  "Slope forest cover", "Cobertura de bosques en pendiente", "Cobertura de boscos en pendent",
  "", "", "",
  "admin_municipality", "static", "-",
  "Municipality", "Municipio", "Municipi",
  "", "", "",
  "admin_region", "static", "-",
  "County", "Comarca", "Comarca",
  "", "", "",
  "admin_province", "static", "-",
  "Province", "Provincia", "Provincia",
  "", "", "",
  "admin_natural_interest_area", "static", "-",
  "Natural interest areas", "Áreas de interés natural","Àrees d'interès natural",
  "", "", "",
  "admin_special_protection_natural_area", "static", "-",
  "Special protection natural areas", "Áreas naturales de protección especial","Àrees naturals de protecció especial",
  "", "", "",
  "admin_natura_network_2000", "static", "-",
  "Natura 2000 network", "Red Natura 2000","Xarxa Natura 2000",
  "", "", "",
  # dynamic tables
  # ifn 2
  "plot_id", "plot_nfi_2_results", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "erosion_mitigation", "plot_nfi_2_results", "t/ha/year",
  "Erosion mitigation", "Erosión mitigada", "Erosió mitigada",
  "", "", "",
  "mushrooms_production", "plot_nfi_2_results", "kg/ha/year",
  "Mushroom production", "Producción de setas", "Producció de bolets",
  "", "", "",
  "exported_water", "plot_nfi_2_results", "blue water/precipitation ratio",
  "Exported water", "Agua exportada", "Aigua exportada",
  "", "", "",
  "admin_municipality", "plot_nfi_2_results", "-",
  "Municipality", "Municipio", "Municipi",
  "", "", "",
  "admin_region", "plot_nfi_2_results", "-",
  "County", "Comarca", "Comarca",
  "", "", "",
  "admin_province", "plot_nfi_2_results", "-",
  "Province", "Provincia", "Provincia",
  "", "", "",
  "admin_natural_interest_area", "plot_nfi_2_results", "-",
  "Natural interest areas", "Áreas de interés natural","Àrees d'interès natural",
  "", "", "",
  "admin_special_protection_natural_area", "plot_nfi_2_results", "-",
  "Special protection natural areas", "Áreas naturales de protección especial","Àrees naturals de protecció especial",
  "", "", "",
  "admin_natura_network_2000", "plot_nfi_2_results", "-",
  "Natura 2000 network", "Red Natura 2000","Xarxa Natura 2000",
  "", "", "",
  # ifn 3
  "plot_id", "plot_nfi_3_results", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "erosion_mitigation", "plot_nfi_3_results", "t/ha/year",
  "Erosion mitigation", "Erosión mitigada", "Erosió mitigada",
  "", "", "",
  "mushrooms_production", "plot_nfi_3_results", "kg/ha/year",
  "Mushroom production", "Producción de setas", "Producció de bolets",
  "", "", "",
  "exported_water", "plot_nfi_3_results", "blue water/precipitation ratio",
  "Exported water", "Agua exportada", "Aigua exportada",
  "", "", "",
  "carbon_sequestration", "plot_nfi_3_results", "t/ha/year",
  "Carbon sequestration", "Carbono secuestrado", "Carboni segrestat",
  "", "", "",
  "wood", "plot_nfi_3_results", "m3/ha/year",
  "Wood production", "Producción de madera", "Producció de fusta",
  "", "", "",
  "admin_municipality", "plot_nfi_3_results", "-",
  "Municipality", "Municipio", "Municipi",
  "", "", "",
  "admin_region", "plot_nfi_3_results", "-",
  "County", "Comarca", "Comarca",
  "", "", "",
  "admin_province", "plot_nfi_3_results", "-",
  "Province", "Provincia", "Provincia",
  "", "", "",
  "admin_natural_interest_area", "plot_nfi_3_results", "-",
  "Natural interest areas", "Áreas de interés natural","Àrees d'interès natural",
  "", "", "",
  "admin_special_protection_natural_area", "plot_nfi_3_results", "-",
  "Special protection natural areas", "Áreas naturales de protección especial","Àrees naturals de protecció especial",
  "", "", "",
  "admin_natura_network_2000", "plot_nfi_3_results", "-",
  "Natura 2000 network", "Red Natura 2000","Xarxa Natura 2000",
  "", "", "",
  # ifn 4
  "plot_id", "plot_nfi_4_results", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "erosion_mitigation", "plot_nfi_4_results", "t/ha/year",
  "Erosion mitigation", "Erosión mitigada", "Erosió mitigada",
  "", "", "",
  "mushrooms_production", "plot_nfi_4_results", "kg/ha/year",
  "Mushroom production", "Producción de setas", "Producció de bolets",
  "", "", "",
  "exported_water", "plot_nfi_4_results", "blue water/precipitation ratio",
  "Exported water", "Agua exportada", "Aigua exportada",
  "", "", "",
  "carbon_sequestration", "plot_nfi_4_results", "t/ha/year",
  "Carbon sequestration", "Carbono secuestrado", "Carboni segrestat",
  "", "", "",
  "wood", "plot_nfi_4_results", "m3/ha/year",
  "Wood production", "Producción de madera", "Producció de fusta",
  "", "", "",
  "admin_municipality", "plot_nfi_4_results", "-",
  "Municipality", "Municipio", "Municipi",
  "", "", "",
  "admin_region", "plot_nfi_4_results", "-",
  "County", "Comarca", "Comarca",
  "", "", "",
  "admin_province", "plot_nfi_4_results", "-",
  "Province", "Provincia", "Provincia",
  "", "", "",
  "admin_natural_interest_area", "plot_nfi_4_results", "-",
  "Natural interest areas", "Áreas de interés natural","Àrees d'interès natural",
  "", "", "",
  "admin_special_protection_natural_area", "plot_nfi_4_results", "-",
  "Special protection natural areas", "Áreas naturales de protección especial","Àrees naturals de protecció especial",
  "", "", "",
  "admin_natura_network_2000", "plot_nfi_4_results", "-",
  "Natura 2000 network", "Red Natura 2000","Xarxa Natura 2000",
  "", "", "",
  # comp 2 3
  "plot_id", "plot_nfi2_nfi3_results", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "erosion_mitigation", "plot_nfi2_nfi3_results", "t/ha/year",
  "Erosion mitigation", "Erosión mitigada", "Erosió mitigada",
  "", "", "",
  "mushrooms_production", "plot_nfi2_nfi3_results", "kg/ha/year",
  "Mushroom production", "Producción de setas", "Producció de bolets",
  "", "", "",
  "exported_water", "plot_nfi2_nfi3_results", "blue water/precipitation ratio",
  "Exported water", "Agua exportada", "Aigua exportada",
  "", "", "",
  "admin_municipality", "plot_nfi2_nfi3_results", "-",
  "Municipality", "Municipio", "Municipi",
  "", "", "",
  "admin_region", "plot_nfi2_nfi3_results", "-",
  "County", "Comarca", "Comarca",
  "", "", "",
  "admin_province", "plot_nfi2_nfi3_results", "-",
  "Province", "Provincia", "Provincia",
  "", "", "",
  "admin_natural_interest_area", "plot_nfi2_nfi3_results", "-",
  "Natural interest areas", "Áreas de interés natural","Àrees d'interès natural",
  "", "", "",
  "admin_special_protection_natural_area", "plot_nfi2_nfi3_results", "-",
  "Special protection natural areas", "Áreas naturales de protección especial","Àrees naturals de protecció especial",
  "", "", "",
  "admin_natura_network_2000", "plot_nfi2_nfi3_results", "-",
  "Natura 2000 network", "Red Natura 2000","Xarxa Natura 2000",
  "", "", "",
  # comp 3 4
  "plot_id", "plot_nfi3_nfi4_results", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "erosion_mitigation", "plot_nfi3_nfi4_results", "t/ha/year",
  "Erosion mitigation", "Erosión mitigada", "Erosió mitigada",
  "", "", "",
  "mushrooms_production", "plot_nfi3_nfi4_results", "kg/ha/year",
  "Mushroom production", "Producción de setas", "Producció de bolets",
  "", "", "",
  "exported_water", "plot_nfi3_nfi4_results", "blue water/precipitation ratio",
  "Exported water", "Agua exportada", "Aigua exportada",
  "", "", "",
  "carbon_sequestration", "plot_nfi3_nfi4_results", "t/ha/year",
  "Carbon sequestration", "Carbono secuestrado", "Carboni segrestat",
  "", "", "",
  "wood", "plot_nfi3_nfi4_results", "m3/ha/year",
  "Wood production", "Producción de madera", "Producció de fusta",
  "", "", "",
  "admin_municipality", "plot_nfi3_nfi4_results", "-",
  "Municipality", "Municipio", "Municipi",
  "", "", "",
  "admin_region", "plot_nfi3_nfi4_results", "-",
  "County", "Comarca", "Comarca",
  "", "", "",
  "admin_province", "plot_nfi3_nfi4_results", "-",
  "Province", "Provincia", "Provincia",
  "", "", "",
  "admin_natural_interest_area", "plot_nfi3_nfi4_results", "-",
  "Natural interest areas", "Áreas de interés natural","Àrees d'interès natural",
  "", "", "",
  "admin_special_protection_natural_area", "plot_nfi3_nfi4_results", "-",
  "Special protection natural areas", "Áreas naturales de protección especial","Àrees naturals de protecció especial",
  "", "", "",
  "admin_natura_network_2000", "plot_nfi3_nfi4_results", "-",
  "Natura 2000 network", "Red Natura 2000","Xarxa Natura 2000",
  "", "", "",
  # comp 2 4
  "plot_id", "plot_nfi2_nfi4_results", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "erosion_mitigation", "plot_nfi2_nfi4_results", "t/ha/year",
  "Erosion mitigation", "Erosión mitigada", "Erosió mitigada",
  "", "", "",
  "mushrooms_production", "plot_nfi2_nfi4_results", "kg/ha/year",
  "Mushroom production", "Producción de setas", "Producció de bolets",
  "", "", "",
  "exported_water", "plot_nfi2_nfi4_results", "blue water/precipitation ratio",
  "Exported water", "Agua exportada", "Aigua exportada",
  "", "", "",
  "carbon_sequestration", "plot_nfi2_nfi4_results", "t/ha/year",
  "Carbon sequestration", "Carbono secuestrado", "Carboni segrestat",
  "", "", "",
  "wood", "plot_nfi2_nfi4_results", "m3/ha/year",
  "Wood production", "Producción de madera", "Producció de fusta",
  "", "", "",
  "admin_municipality", "plot_nfi2_nfi4_results", "-",
  "Municipality", "Municipio", "Municipi",
  "", "", "",
  "admin_region", "plot_nfi2_nfi4_results", "-",
  "County", "Comarca", "Comarca",
  "", "", "",
  "admin_province", "plot_nfi2_nfi4_results", "-",
  "Province", "Provincia", "Provincia",
  "", "", "",
  "admin_natural_interest_area", "plot_nfi2_nfi4_results", "-",
  "Natural interest areas", "Áreas de interés natural","Àrees d'interès natural",
  "", "", "",
  "admin_special_protection_natural_area", "plot_nfi2_nfi4_results", "-",
  "Special protection natural areas", "Áreas naturales de protección especial","Àrees naturals de protecció especial",
  "", "", "",
  "admin_natura_network_2000", "plot_nfi2_nfi4_results", "-",
  "Natura 2000 network", "Red Natura 2000","Xarxa Natura 2000",
  "", "", ""
)

## code to prepare `app_translations` dataset goes here

app_translations <- tibble::tribble(
  ~text_id, ~translation_cat, ~translation_eng, ~translation_spa,
  # data version choices
  'h4_data_version', "Fixa l'escala", "Select the scale", "Selecciona la escala",
  'data_version', "Escala temporal", "Temporal scale", "Escala temporal",
  'static', 'Dades fixes', 'Static data', 'Datos fijos',
  'dynamic', 'Dades dinamics', 'Dynamic data', 'Datos dinámicos',
  'plot_nfi_2_results', "IFN 2 (~1990)", "NFI 2 (~1990)", "IFN 2 (~1990)",
  'plot_nfi_3_results', "IFN 3 (~2000)", "NFI 3 (~2000)", "IFN 3 (~2000)",
  'plot_nfi_4_results', "IFN 4 (~2014)", "NFI 4 (~2014)", "IFN 4 (~2014)",
  'plot_nfi2_nfi3_results', "IFN 2 : IFN 3 (1990 ~ 2000)", "NFI 2 : NFI 3 (1990 ~ 2000)", "IFN 2 : IFN 3 (1990 ~ 2000)",
  'plot_nfi3_nfi4_results', "IFN 3 : IFN 4 (2000 ~ 2014)", "NFI 3 : NFI 4 (2000 ~ 2014)", "IFN 3 : IFN 4 (2000 ~ 2014)",
  'plot_nfi2_nfi4_results', "IFN 2 : IFN 4 (1990 ~ 2014)", "NFI 2 : NFI 4 (1990 ~ 2014)", "IFN 2 : IFN 4 (1990 ~ 2014)",
  # data scale choices
  'data_scale', 'Escala espacial', 'Spatial scale', 'Escala espacial',
  'local', 'Local', 'Local', 'Local',
  'admin_province', 'Provincia', 'Province', 'Provincia',
  'admin_region', 'Comarca', 'County', 'Comarca',
  'admin_municipality', 'Municipi', 'Municipality', 'Municipio',
  "admin_natural_interest_area", "Àrees d'interès natural", "Natural interest areas", "Áreas de interés natural",
  "admin_special_protection_natural_area", "Àrees naturals de protecció especial", "Special protection natural areas", "Áreas naturales de protección especial",
  "admin_natura_network_2000", "Xarxa Natura 2000", "Natura 2000 network", "Red Natura 2000",
  'drawn_polygon', "Polígon dibuxat", "Drawn polygon", "Polígono dibujado",
  "file", "Arxiu de polìgons", "Polygon file", "Archivo de polígonos",
  "poly_id", "ID polígon", "Polygon ID", "ID polígono",
  # use file selection
  "user_file_sel_label", "Selecciona l'arxiu a carregar", "Select the file to upload", "Selecciona el archivo a cargar",
  "user_file_sel_buttonLabel", "Inspecciona...", "Browse...", "Inspecciona...",
  "user_file_sel_placeholder", "Cap fitxer seleccionat", "No file selected", "Ningún archivo seleccionado",
  "file_text", 'El fitxer pot ser un shapefile (comprimit en un fitxer zip) o un fitxer GeoPackage (.gpkg). Han de tenir un camp anomenat "poly_id" amb els identificadors dels polígons continguts.', 'File can be a shapefile (compressed in a zip file) or GeoPackage file (.gpkg). They must have a field called "poly_id" with the identifiers of the contained polygons.', 'El archivo puede ser un shapefile (comprimido en un archivo zip) o un archivo GeoPackage (.gpkg). Deben tener un campo llamado "poly_id" con los identificadores de los polígonos contenidos.',
  # map
  'Relief', 'Relleu (base)', 'Relief (base)', 'Relieve (base)',
  'Imaginery', 'Satèl·lit (base)', 'Imaginery (base)', 'Satélite (base)',
  "cite_div", "Dades elaborades pel CTFC i el CREAF.", "Data prepared by the CTFC and CREAF.", "Datos elaborados por el CTFC y el CREAF.",
  # tabs translations
  "main_tab_translation", "Explora", "Explore", "Explora",
  "data_translation", "Dades", "Data", "Datos",
  "save_translation", "Guardar", "Save", "Guardar",
  "help_translation", "Ajuda", "Help", "Ayuda",
  "map_translation", "Mapa", "Map", "Mapa",
  "table_translation", "Taula", "Table", "Tabla",
  # metric choices
  'mean', 'Mitjana', 'Mean', 'Media',
  'min', 'Minim', 'Minimum', 'Mínimo',
  'max', 'Maxim', 'Maximum', 'Máximo',
  'se', 'ES', 'SE', 'ES',
  'q05', 'Quartil 5', 'Quantile 5', 'Cuartil 5',
  'q95', 'Quartil 95', 'Quantile 95', 'Cuartil 95',
  'n', 'Nombre parcel·las', 'Plot number', 'Número de parcelas',
  # _metric
  '_mean', ' mitjana', ' mean', ' media',
  '_min', ' minim ', ' minimum', ' mínimo',
  '_max', ' maxim', ' maximum', ' máximo de ',
  '_se', ' ES', ' SE', ' ES',
  '_q05', ' quartil 5', ' quantile 5', ' cuartil 5',
  '_q95', ' quartil 95', ' quantile 95', ' cuartil 95',
  '_n', ' nombre parcel·las', ' plot number', ' número de parcelas',
  # viz
  "h4_viz", "Visualització", "Visualization", "Visualización",
  "deselect-all-text", "Ningú", "None selected...", "Ninguno",
  "select-all-text", "Tots", "All selected...", "Todos",
  "count-selected-text-value", "{0} valors seleccionats (de {1})", "{0} values selected (of {1})", "{0} valores seleccionados (de {1})",
  "viz_color_input", "Servei ecosistemic:", "Ecosystem service:", "Servicio ecosistémico:",
  "viz_statistic_input", "Estadístic:", "Statistic:", "Estadístico:",
  "pal_high", "Discriminar valors alts", "Discriminate higher values", "Discriminar valores altos",
  "pal_low", "Discriminar valors baixos", "Discriminate lower values", "Discriminar valores bajos",
  "pal_normal", "Normal", "Normal", "Normal",
  "viz_pal_config_input", "Configurar paleta", "Config palette", "Configurar paleta",
  "viz_pal_reverse_input", "Invertir la paleta?", "Reverse the palette?", "¿Invertir la paleta?",
  # save
  'save_map_btn', "Guarda el map", "Save the map", "Guarda el mapa",
  'save_table_btn', "Guarda la taula", "Save the table", "Guarda la tabla",
  "csv", "Text (csv)", "Text (csv)", "Texto (csv)",
  "xlsx", "MS Excel (xlsx)", "MS Excel (xlsx)", "MS Excel (xlsx)",
  "table_output_options_input", "Selecciona el format", "Choose the output format", "Selecciona el formato",
  "glossary_var_input", "Selecciona el servei a descriure", "Choose the service to describe", "Selecciona el servicio a describir",
  "link_to_tutorials_text", "Per obtenir més informació, aneu al tutorial de l'aplicació aquí", "For more info, please go to the application tutorial here", "Para obtener más información, vaya al tutorial de la aplicación aquí.",
  "var_description_title", "Descripció:", "Description:", "Descripción:",
  "var_units_title", "Unitats:", "Units:", "Unidades:",
  # info module
  "plot_id_info_plot_title", "Parcel·la seleccionada comparada amb les altres parcel·les al mapa", "Clicked plot compared to other plots in map", "Parcela seleccionada comparada con las otras parcelas en el mapa",
  "admin_region_info_plot_title", "Comarca seleccionada comparada amb les altres comarques al mapa", "Clicked region compared to other regions in map", "Comarca seleccionada comparada con las otras comarcas en el mapa",
  "admin_municipality_info_plot_title", "Municipi seleccionado comparad amb els altres municipis al mapa", "Clicked municipality compared to other municipalities in map", "Municipio seleccionada comparada con los otros municipios en el mapa",
  "poly_id_info_plot_title", "Polìgon seleccionado comparado amb les altres polìgons al mapa", "Clicked polygon compared to other polygons in map", "Polígono seleccionada comparada con los otros polígonos en el mapa",
  "admin_natura_network_2000_info_plot_title", "Àrea seleccionada comparada amb les altres àreas al mapa", "Clicked natural area compared to other natural areas in map", "Área seleccionada comparada con las otras áreas en el mapa",
  "admin_special_protection_natural_area_info_plot_title", "Àrea seleccionada comparada amb les altres àreas al mapa", "Clicked natural area compared to other natural areas in map", "Área seleccionada comparada con las otras áreas en el mapa",
  "admin_natural_interest_area_info_plot_title", "Àrea seleccionada comparada amb les altres àreas al mapa", "Clicked natural area compared to other natural areas in map", "Área seleccionada comparada con las otras áreas en el mapa",
  # progress bar
  "progress_message", "Obtenció de dades...", "Obtaining data...", "Obteniendo datos...",
  "progress_detail_initial", "Escalant les dades", "Data scaling", "Escalando los datos",
)
