library(tibble)
# variable thesaurus
variable_thesaurus <- tibble::tribble(
  # headers
  ~var_id, ~var_table, ~var_units,
  ~translation_eng, ~translation_spa, ~translation_cat,
  ~var_description_eng, ~var_description_spa, ~var_description_cat,
  # static table
  "animals_presence", "static", "count",
  "Animals presence", "Presencia de animales", "Presència d'animals",
  "", "", "",
  "mushrooms_production", "static", "kg",
  "Mushroom production", "Producción de setas", "Producció de bolets",
  "", "", "",
  "exported_water", "static", "",
  "Exported water", "Agua exportada", "Aigua exportada",
  "", "", "",
  "carbon_sequestration", "static", "",
  "Carbon sequestration", "Carbono secuestrado", "Carboni segrestat",
  "", "", "",
  "soil_organic_carbon", "static", "",
  "Soil organic carbon", "Carbono orgánico del suelo", "Carboni orgànic del sòl",
  "", "", "",
  "riparian_forest_cover", "static", "%",
  "Riparian forest cover", "Cobertura de bosques de ribera", "Cobertura de boscos de ribera",
  "", "", "",
  "slope_forest_cover", "static", "%",
  "Slope forest cover", "Cobertura de bosques en pendiente", "Cobertura de boscos en pendent",
  "", "", "",
  "admin_municipality", "static", "-",
  "Municipality", "Municipio", "Municipi",
  "", "", "",
  "admin_region", "static", "-",
  "County", "Comarca", "Comarca",
  "", "", "",
  "admin_province", "static", "-",
  "Province", "Provincia", "Provincia",
  "", "", "",
  # dynamic tables
  # ifn 2
  "plot_id", "plot_nfi_2_results", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "erosion_control", "plot_nfi_2_results", "",
  "Erosion control", "Control de erosión", "Control de erosió",
  "", "", "",
  "mushrooms_production", "plot_nfi_2_results", "kg",
  "Mushroom production", "Producción de setas", "Producció de bolets",
  "", "", "",
  "exported_water", "plot_nfi_2_results", "",
  "Exported water", "Agua exportada", "Aigua exportada",
  "", "", "",
  # ifn 3
  "plot_id", "plot_nfi_3_results", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "erosion_control", "plot_nfi_3_results", "",
  "Erosion control", "Control de erosión", "Control de erosió",
  "", "", "",
  "mushrooms_production", "plot_nfi_3_results", "kg",
  "Mushroom production", "Producción de setas", "Producció de bolets",
  "", "", "",
  "exported_water", "plot_nfi_3_results", "",
  "Exported water", "Agua exportada", "Aigua exportada",
  "", "", "",
  # ifn 4
  "plot_id", "plot_nfi_4_results", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "erosion_control", "plot_nfi_4_results", "",
  "Erosion control", "Control de erosión", "Control de erosió",
  "", "", "",
  "mushrooms_production", "plot_nfi_4_results", "kg",
  "Mushroom production", "Producción de setas", "Producció de bolets",
  "", "", "",
  "exported_water", "plot_nfi_4_results", "",
  "Exported water", "Agua exportada", "Aigua exportada",
  "", "", "",
  # comp 2 3
  "plot_id", "plot_nfi2_nfi3_results", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "soil_organic_carbon", "plot_nfi2_nfi3_results", "",
  "Soil organic carbon", "Carbono orgánico del suelo", "Carboni orgànic del sòl",
  "", "", "",
  "wood", "plot_nfi2_nfi3_results", "",
  "Wood production", "Producción de madera", "Producció de fusta",
  "", "", "",
  # comp 3 4
  "plot_id", "plot_nfi3_nfi4_results", "-",
  "Plot ID", "ID de parcela", "ID de parcel·la",
  "", "", "",
  "soil_organic_carbon", "plot_nfi3_nfi4_results", "",
  "Soil organic carbon", "Carbono orgánico del suelo", "Carboni orgànic del sòl",
  "", "", "",
  "wood", "plot_nfi3_nfi4_results", "",
  "Wood production", "Producción de madera", "Producció de fusta",
  "", "", ""
)
